All: ContactsApp.class

ContactsApp.class: Contact.java ContactsApp.java
	javac -cp .:..:../lanterna-3.0.0.jar Contact.java
	javac -cp .:..:../lanterna-3.0.0.jar ContactsApp.java

run:
	java -cp .:..:../lanterna-3.0.0.jar ContactsApp

clean:
	rm *.class

