All: ContactsApp.class

ContactsApp.class: BusinessContact.java ContactsApp.java
	javac -cp .:..:../lanterna-3.0.0.jar BusinessContact.java
	javac -cp .:..:../lanterna-3.0.0.jar ContactsApp.java

run:
	java -cp .:..:../lanterna-3.0.0.jar ContactsApp

clean:
	rm *.class

